import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#09090b] text-zinc-300 py-24 px-4 sm:px-8">
      <div className="max-w-4xl mx-auto prose prose-invert prose-emerald text-justify">
        <h1>Terms and Conditions for IdeeaTa.ai</h1>
        <p><strong>Last updated:</strong> June 2026</p>
        
        <p>Welcome to <strong>IdeeaTa.ai</strong>! These Terms and Conditions govern your access to and use of the IdeeaTa.ai web platform and associated services. By accessing or using our platform, you agree to comply with these Terms. If you do not agree with them, please do not use the service.</p>

        <h2>1. Description of Service</h2>
        <p>IdeeaTa.ai is an Artificial Intelligence-powered Software-as-a-Service (SaaS) platform that helps entrepreneurs generate business plan models, structures, budget estimates, and SWOT analyses.</p>

        <h2>2. Disclaimer and Lack of Commercial / Financial Warranties</h2>
        <div className="bg-red-950/30 border border-red-900/50 p-4 rounded-xl my-6">
          <p className="text-red-400 font-bold mt-0 mb-2">IMPORTANT</p>
          <p className="mb-0">IdeeaTa.ai is a <strong>strictly informational and educational</strong> tool. We are not financial advisors, lawyers, or accountants.</p>
        </div>
        <ul>
          <li><strong>No Guarantees of Success:</strong> We do not guarantee that applying the ideas or business plans generated on this platform will bring profit, financing, or commercial success.</li>
          <li><strong>Data Accuracy (AI):</strong> Information, budget estimates, and financial projections are generated by an Artificial Intelligence algorithm based on general market averages. We assume no liability for the accuracy of these estimates. It is your sole responsibility to validate the plan with authorized experts before investing money or requesting funds.</li>
        </ul>

        <h2>3. User Account</h2>
        <p>To use certain features (such as saving plans or premium features), you must create an account authenticated via Google, Facebook, or Email.</p>
        <ul>
          <li>You are responsible for the confidentiality of your login details.</li>
          <li>We reserve the right to suspend accounts that abuse the system (e.g., automated generation/spam of documents to exhaust AI resources).</li>
        </ul>

        <h2>4. Payments and Refund Policy</h2>
        <ul>
          <li><strong>Payment Processing:</strong> Payments to unlock premium features (e.g., "Interactive AI Studio", special exports) are processed securely exclusively through our partner <strong>Lemon Squeezy</strong>.</li>
          <li><strong>No Refunds:</strong> Due to the digital and consumable nature of our services (non-recoverable AI processing costs for each generation), <strong>all purchases are final</strong>. No refunds are offered after the plan or feature unlock has been completed, unless the service was technically unavailable due to our fault.</li>
        </ul>

        <h2>5. Intellectual Property</h2>
        <ul>
          <li><strong>Generated Data:</strong> You become the owner of the documents (PDF, DOCX, PPTX) and texts you download and can use them for any commercial or personal purpose you wish.</li>
          <li><strong>Platform:</strong> The source code, design, graphic interface, and brand "IdeeaTa.ai" belong entirely to us and cannot be copied or reproduced.</li>
        </ul>

        <h2>6. Limitation of Liability</h2>
        <p>IdeeaTa.ai will not be liable for any direct, indirect, incidental, or consequential damages, or loss of profits, reputation, or data resulting from:</p>
        <ul>
          <li>The use or inability to use the service.</li>
          <li>Acting on the financial plans generated by the system.</li>
          <li>Unauthorized access to our servers where your plans are stored.</li>
        </ul>

        <h2>7. Changes to the Terms</h2>
        <p>We reserve the right to modify these terms at any time. Significant changes will be notified on the platform. Continued use after the change represents your acceptance.</p>

        <h2>8. Contact Data</h2>
        <p>For any questions regarding these Terms, please contact us at: <a href="mailto:contact@ideeata.ai" className="text-emerald-400">contact@ideeata.ai</a>.</p>
        
        <div className="flex justify-center mt-12 mb-12">
          <Link href="/en/demo" className="bg-emerald-600 hover:bg-emerald-500 text-white px-8 py-4 rounded-xl font-bold transition-all shadow-lg shadow-emerald-900/30 no-underline">
            Validate your idea right now
          </Link>
        </div>
      </div>
    </div>
  );
}
