export interface BusinessExample {
  short: string;
  long: string;
}

export const ALL_EXAMPLES_RO: BusinessExample[] = [
  { short: "Brutărie Tradițională", long: "O brutărie și patiserie tradițională, axată pe pâine cu maia și rețete locale autentice." },
  { short: "Spălătorie Auto", long: "O spălătorie auto self-service modernă, cu jet de înaltă presiune și spumă activă biodegradabilă." },
  { short: "Salon Înfrumusețare", long: "Un salon de înfrumusețare și frizerie complet, care oferă servicii premium de styling și tratamente." },
  { short: "Restaurant Tradițional", long: "Un restaurant cu specific tradițional românesc, cu un meniu bazat exclusiv pe ingrediente de la producători locali." },
  { short: "Firmă de Curățenie", long: "O firmă de curățenie profesională B2B și B2C, folosind exclusiv detergenți ecologici și echipamente silențioase." },
  { short: "Magazin Mixt", long: "Un magazin mixt de cartier cu funcționare non-stop, optimizat pentru cumpărături rapide." },
  { short: "Atelier Auto", long: "Un atelier auto și vulcanizare care oferă servicii rapide, diagnoză computerizată și asistență rutieră." },
  { short: "Firmă de Construcții", long: "O firmă de construcții și amenajări interioare, specializată în renovări la cheie și finisaje premium." },
  { short: "Cabinet Stomatologic", long: "Un cabinet stomatologic modern echipat cu tehnologie 3D și specializat în implantologie." },
  { short: "Contabilitate", long: "O firmă de contabilitate complet digitalizată, dedicată startup-urilor și IMM-urilor." },
  { short: "Farmacie de Cartier", long: "O farmacie de cartier care oferă consultanță personalizată și preparate magistrale." },
  { short: "Veterinar Non-Stop", long: "Un cabinet veterinar cu program non-stop, dotat cu ecograf, raze X și laborator propriu." },
  { short: "Servicii de Mutări", long: "O firmă de servicii de mutări și relocare ce oferă inclusiv servicii de ambalare și demontare." },
  { short: "Agenție Imobiliară", long: "O agenție imobiliară de nișă, axată exclusiv pe apartamente premium și ansambluri rezidențiale noi." },
  { short: "Fermă Agricolă", long: "O fermă agricolă mixtă, concentrată pe culturi organice și distribuție direct către consumator." },
  
  { short: "Matcha Bar & Cafenea", long: "Un matcha bar și cafenea de specialitate cu un design minimalist, oferind băuturi pe bază de ceai premium." },
  { short: "Studio de Pilates", long: "Un studio de pilates și yoga boutique cu clase restrânse și antrenamente personalizate." },
  { short: "Parfumuri Personalizate", long: "Un atelier de parfumuri personalizate unde clienții își creează propriile esențe unice." },
  { short: "Boutique Vintage", long: "Un boutique cu haine vintage selecționate și recondiționate, promovând moda sustenabilă." },
  { short: "Design Românesc", long: "Un concept store dedicat exclusiv designerilor români, de la haine la obiecte de decor." },
  { short: "Florărie Minimalistă", long: "O florărie minimalistă care oferă abonamente lunare de flori proaspete pentru birouri și acasă." },
  { short: "Cofetărie French", long: "O cofetărie artizanală de inspirație franceză, specializată în eclere și macarons." },
  { short: "Design Interior", long: "Un studio de design interior și arhitectură axat pe spații rezidențiale ecologice și soluții smart-home." },
  { short: "Cosmetică Organică", long: "Un salon de cosmetică organică ce folosește exclusiv produse naturale, cruelty-free." },
  { short: "Galerie & Cafenea", long: "O galerie de artă contemporană combinată cu o cafenea de specialitate, un spațiu creativ." },
  { short: "Vinuri & Brânzeturi", long: "Un magazin specializat în vinuri rare și brânzeturi fine, cu zonă de degustare." },
  { short: "Planificare Nunți", long: "O agenție de planificare a nuților de lux, axată pe evenimente tematice unice." },
  { short: "Ceramică Artizanală", long: "Un atelier de ceramică unde se produc obiecte unicat și se organizează workshop-uri." },
  
  { short: "Arenă E-Sports", long: "Un studio și arenă de e-sports dotată cu PC-uri high-end și echipamente profesionale." },
  { short: "Cafenea Board Games", long: "O cafenea dedicată pasionaților de board games și jocuri retro, cu bibliotecă de jocuri." },
  { short: "Agenție TikTok", long: "O agenție de influencer marketing specializată în campanii virale pe TikTok." },
  { short: "Sneakers Resale", long: "Un magazin de resale și autentificare pentru sneakers rari și ediții limitate." },
  { short: "Aplicație de Dating", long: "O aplicație de dating inovatoare bazată pe interese comune și hobby-uri specifice." },
  { short: "E-learning Financiar", long: "O platformă de e-learning dedicată educației financiare și investițiilor pentru tineri." },
  { short: "Streetwear Sustenabil", long: "Un brand de haine streetwear produs exclusiv din materiale reciclate și sustenabile." },
  { short: "Creare Conținut UGC", long: "O agenție care oferă servicii de creare conținut video autentic generat de utilizatori (UGC)." },
  { short: "Coworking Nomazi", long: "Un hub de coworking conceput special pentru nevoile nomazilor digitali și freelancerilor." },
  { short: "Platformă Freelancing", long: "O platformă de freelancing strict pentru specialiști locali verificați manual." },
  { short: "Jocuri Video Indie", long: "Un studio independent de dezvoltare jocuri video axat pe povești interactive." },
  { short: "Arhitectură Minimalistă", long: "Un birou de arhitectură minimalistă, concentrat pe case pasive și eficiente energetic." },
  
  { short: "Hotel de Plante", long: "Un serviciu de îngrijire și 'hotel' pentru plante de apartament pe durata vacanțelor." },
  { short: "Catering pe Baza ADN", long: "Un serviciu premium de catering cu meniu ultra-personalizat pe baza analizei ADN." },
  { short: "Ambalaje din Miceliu", long: "O fabrică de producție de ambalaje 100% biodegradabile din miceliu (ciuperci)." },
  { short: "AI Limbajul Semnelor", long: "O aplicație software bazată pe AI pentru traducerea în timp real a limbajului semnelor." },
  { short: "Matchmaking Co-fondatori", long: "O platformă inteligentă de matchmaking pentru a găsi partenerul ideal de afaceri." },
  { short: "Fermă Hidroponică", long: "O fermă hidroponică urbană de microplante, furnizând direct către restaurante de top." },
  { short: "Design Peisagistic", long: "Servicii de design peisagistic specializate strict pentru balcoane și terase urbane." },
  { short: "Conversie Mașini Clasice", long: "Un atelier dedicat conversiei mașinilor clasice pe benzină în vehicule 100% electrice." },
  { short: "Mobilier AR", long: "O aplicație de realitate augmentată care permite probarea mobilierului direct în casă." },
  { short: "Reciclare Baterii", long: "O stație avansată de recuperare și reciclare a bateriilor de la mașinile electrice." },
  { short: "Telemedicină Veterinară", long: "O platformă de telemedicină și triaj virtual pentru urgențele animalelor de companie." },
  
  { short: "Securitate Cibernetică", long: "O firmă de consultanță în securitate cibernetică specializată în audituri și teste de penetrare." },
  { short: "Analiză de Risc", long: "O companie care oferă servicii de analiză de risc instituțional pentru corporații." },
  { short: "Soluții AI", long: "O agenție de dezvoltare software axată pe implementarea soluțiilor de Inteligență Artificială." },
  { short: "Fonduri Europene", long: "O firmă de consultanță specializată în redactarea de proiecte pentru obținerea de fonduri europene." },
  { short: "Marketing Digital", long: "O agenție de marketing digital integrat, de la SEO și Google Ads până la Social Media." },
  { short: "Cursuri Online", long: "O platformă agregator de cursuri online cu certificare recunoscută." },
  { short: "Magazin Produse Bio", long: "Un magazin online dedicat exclusiv produselor alimentare certificate bio și ecologice." },
  { short: "Aplicație de Fitness", long: "O aplicație mobilă de fitness cu antrenor virtual bazat pe AI." },
  { short: "Consultanță Nutriție", long: "Un cabinet online de consultanță în nutriție cu planuri de mese personalizate." },
  { short: "Livrare Vegană", long: "Un serviciu de livrare de mâncare 100% vegană bazată pe rețete gourmet." },
  { short: "Biciclete Electrice", long: "Un sistem de închiriere de biciclete și trotinete electrice pentru turism urban." },
  { short: "SEO B2B", long: "O agenție specializată în optimizare SEO tehnică pentru companiile B2B." },
  { short: "Aplicații Mobile", long: "Un studio de dezvoltare nativă de aplicații mobile pentru iOS și Android." },
  { short: "Juridică Online", long: "O platformă care oferă servicii de asistență și consultanță juridică online rapidă." }
];

export const ALL_EXAMPLES_EN: BusinessExample[] = [
  { short: "Traditional Bakery", long: "A traditional bakery and pastry shop, focused on sourdough bread and authentic local recipes." },
  { short: "Self-Service Car Wash", long: "A modern self-service car wash, with high-pressure jet and biodegradable active foam." },
  { short: "Beauty Salon", long: "A complete beauty and hair salon, offering premium styling and treatment services." },
  { short: "Traditional Restaurant", long: "A restaurant with traditional local specificity, with a menu based exclusively on ingredients from local producers." },
  { short: "Cleaning Services", long: "A professional B2B and B2C cleaning company, using exclusively eco-friendly detergents and silent equipment." },
  { short: "Convenience Store", long: "A modern 24/7 convenience store, optimized for quick shopping." },
  { short: "Auto Repair Shop", long: "An auto repair and tire shop offering fast services, computer diagnostics, and roadside assistance." },
  { short: "Construction Company", long: "A construction and interior design company, specializing in turnkey renovations and premium finishes." },
  { short: "Dental Clinic", long: "A modern dental clinic equipped with 3D technology and specializing in implantology." },
  { short: "Accounting Firm", long: "A fully digitalized accounting firm, dedicated to startups and SMEs." },
  { short: "Local Pharmacy", long: "A local pharmacy offering personalized advice and custom formulations." },
  { short: "24/7 Veterinary Clinic", long: "A veterinary clinic with 24/7 service, equipped with ultrasound, X-ray and own lab." },
  { short: "Moving Services", long: "A moving and relocation services company that also offers packing and disassembly services." },
  { short: "Real Estate Agency", long: "A niche real estate agency, focused exclusively on premium apartments and new residential complexes." },
  { short: "Organic Farm", long: "A mixed agricultural farm, focused on organic crops and direct distribution to consumers." },
  
  { short: "Matcha Bar & Café", long: "A minimalist matcha bar and specialty coffee shop, offering premium tea-based drinks." },
  { short: "Pilates Studio", long: "A boutique pilates and yoga studio with small classes and personalized training." },
  { short: "Custom Perfumes", long: "A custom perfume workshop where customers create their own unique scents." },
  { short: "Vintage Boutique", long: "A boutique with selected and restored vintage clothes, promoting sustainable fashion." },
  { short: "Local Designer Store", long: "A concept store dedicated exclusively to local designers, from clothing to home decor." },
  { short: "Minimalist Florist", long: "A minimalist florist offering monthly flower subscriptions for offices and homes." },
  { short: "Artisan French Patisserie", long: "An artisan pastry shop of French inspiration, specializing in eclairs and macarons." },
  { short: "Interior Design Studio", long: "An interior design and architecture studio focused on ecological residential spaces and smart-home solutions." },
  { short: "Organic Cosmetics Salon", long: "An organic beauty salon using exclusively natural, cruelty-free products." },
  { short: "Art Gallery & Café", long: "A contemporary art gallery combined with a specialty coffee shop, a creative space." },
  { short: "Wine & Cheese Shop", long: "A shop specializing in rare wines and fine cheeses, with a tasting area." },
  { short: "Wedding Planner", long: "A luxury wedding planning agency, focused on unique themed events." },
  { short: "Artisan Pottery Workshop", long: "A pottery workshop producing unique items and organizing workshops." },
  
  { short: "E-Sports Arena", long: "A gaming center and e-sports arena equipped with high-end PCs and professional gear." },
  { short: "Board Game Café", long: "A café dedicated to board games and retro gaming, with a large library of games." },
  { short: "TikTok Marketing Agency", long: "An influencer marketing agency specializing in viral TikTok campaigns." },
  { short: "Sneakers Resell Shop", long: "A resell and authentication store for rare sneakers and limited editions." },
  { short: "Dating App", long: "An innovative dating application based on common interests and specific hobbies." },
  { short: "Financial E-learning Platform", long: "An e-learning platform dedicated to financial education and investing for youth." },
  { short: "Sustainable Streetwear", long: "A streetwear brand produced exclusively from recycled and sustainable materials." },
  { short: "UGC Content Agency", long: "An agency offering authentic User Generated Content (UGC) video creation services." },
  { short: "Digital Nomad Coworking", long: "A coworking hub designed specifically for digital nomads and freelancers." },
  { short: "Freelance Platform", long: "A freelancing platform strictly for manually verified local specialists." },
  { short: "Indie Game Studio", long: "An independent game development studio focused on interactive stories." },
  { short: "Minimalist Architecture", long: "A minimalist architecture firm focused on passive and energy-efficient homes." },
  
  { short: "Plant Hotel", long: "A plant care and 'hotel' service for indoor plants during vacations." },
  { short: "DNA-Based Catering", long: "A premium catering service with an ultra-personalized menu based on DNA analysis." },
  { short: "Mycelium Packaging", long: "A factory producing 100% biodegradable packaging from mycelium (mushrooms)." },
  { short: "Sign Language AI", long: "An AI-based software application for real-time translation of sign language." },
  { short: "Co-founder Matchmaking", long: "An intelligent matchmaking platform to find the ideal business partner." },
  { short: "Hydroponic Farm", long: "An urban hydroponic microgreen farm supplying directly to top restaurants." },
  { short: "Urban Landscaping", long: "Landscape design services specialized strictly for urban balconies and terraces." },
  { short: "Classic Car EV Conversion", long: "A workshop dedicated to converting classic petrol cars into 100% electric vehicles." },
  { short: "AR Furniture App", long: "An augmented reality app allowing users to try furniture directly in their home." },
  { short: "EV Battery Recycling", long: "An advanced recovery and recycling station for electric vehicle batteries." },
  { short: "Pet Telemedicine", long: "A telemedicine and virtual triage platform for pet emergencies." },
  
  { short: "Cybersecurity Firm", long: "A cybersecurity consulting firm specializing in audits and penetration testing." },
  { short: "Risk Assessment Company", long: "A company offering institutional risk assessment services for corporations." },
  { short: "AI Solutions Agency", long: "A software development agency focused on implementing Artificial Intelligence solutions." },
  { short: "Grant Writing Agency", long: "A consulting firm specialized in drafting projects for securing public/EU funds." },
  { short: "Digital Marketing Agency", long: "An integrated digital marketing agency, from SEO and Google Ads to Social Media." },
  { short: "Online Courses Aggregator", long: "An online course aggregator platform with recognized certification." },
  { short: "Organic E-shop", long: "An online store dedicated exclusively to certified organic and ecological food products." },
  { short: "Fitness App", long: "A mobile fitness application with a virtual trainer based on AI." },
  { short: "Nutrition Consulting", long: "An online nutrition consulting clinic with personalized meal plans." },
  { short: "Vegan Food Delivery", long: "A 100% vegan food delivery service based on gourmet recipes." },
  { short: "E-Bike Rental System", long: "An electric bike and scooter rental system for urban tourism." },
  { short: "B2B SEO Agency", long: "An agency specialized in technical SEO optimization for B2B companies." },
  { short: "Mobile App Studio", long: "A native mobile application development studio for iOS and Android." },
  { short: "Online Legal Assistance", long: "A platform providing fast online legal assistance and consulting services." }
];

export function getExamples(locale: "ro" | "en" = "ro"): BusinessExample[] {
  return locale === "en" ? ALL_EXAMPLES_EN : ALL_EXAMPLES_RO;
}
