import { doc, setDoc, increment, arrayUnion } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { jsPDF } from "jspdf";
import { toPng } from "html-to-image";
import { generatePptx } from "@/lib/generatePptx";
import { generateDocxBlob } from "@/lib/generateDocx";

interface UseExportActionsProps {
  result: any;
  locale: "ro" | "en" | "es";
  currency: string;
  user: any;
  isAdmin: boolean;
  isPlanPaid: boolean;
  subscriptionActive: boolean;
  euFundsUnlocked: boolean;
  credits: number;
  setIsDownloading: (mode: any) => void;
  setPendingDownloadMode: (mode: any) => void;
  setShowPricingModal: (show: boolean) => void;
  setIsSharedView: (shared: boolean) => void;
  t: any;
}

export function useExportActions({
  result,
  locale,
  currency,
  user,
  isAdmin,
  isPlanPaid,
  subscriptionActive,
  euFundsUnlocked,
  credits,
  setIsDownloading,
  setPendingDownloadMode,
  setShowPricingModal,
  setIsSharedView,
  t
}: UseExportActionsProps) {
  
  const handleDownloadAction = async (mode: 'pdf' | 'pptx' | 'word' | 'pdf-summary', bypassPaymentCheck = false) => {
    const planName = result?.nume || "Plan de Afaceri";

    if (mode !== 'pdf-summary' && !isAdmin && !isPlanPaid && !subscriptionActive && !euFundsUnlocked && !bypassPaymentCheck) {
      if (!user) {
        window.history.pushState({ login: true }, '', window.location.pathname + '?login=true');
        setIsSharedView(false);
        return;
      }
      if (credits > 0) {
        const confirmUnlock = window.confirm(
          locale === "en"
            ? `Downloading this document will consume 1 credit of the ${credits} available. Do you wish to continue?`
            : locale === "es"
            ? `Descargar este documento consumirá 1 crédito de los ${credits} disponibles. ¿Desea continuar?`
            : `Descărcarea acestui document va consuma 1 credit din cele ${credits} disponibile. Dorești să continui?`
        );
        if (!confirmUnlock) return;

        try {
          const userRef = doc(db, "users", user!.uid);
          await setDoc(userRef, {
            credits: increment(-1),
            unlockedPlans: arrayUnion(planName)
          }, { merge: true });
        } catch (e) {
          console.error("Eroare la scaderea creditului:", e);
          alert(t("errorProcessingCredit", locale));
          return;
        }
      } else {
        setPendingDownloadMode(mode as any);
        setShowPricingModal(true);
        return;
      }
    }
    setIsDownloading(mode as any);
    await new Promise(resolve => setTimeout(resolve, 500));
    try {
      let generatedShareId: string | null = null;
      if (mode === 'pdf-summary' || mode === 'pdf') {
        try {
          const res = await fetch('/api/share', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ planData: result })
          });
          const data = await res.json();
          if (data.id) generatedShareId = data.id;
        } catch (err) {
          console.error("Eroare generare share link:", err);
        }
      }

      if (mode === 'pptx' || mode === 'pdf' || mode === 'pdf-summary') {
        await new Promise(resolve => setTimeout(resolve, 800));
      }

      const safeName = result?.nume?.replace(/[^a-zA-Z0-9]/g, '_') || 'Business';

      if (mode === 'pptx') {
        const planCurrency = result?.selectedCurrency || currency || (locale === "es" || locale === "en" ? "EUR" : "LEI");
        await generatePptx(result, safeName, planCurrency, 0.201, locale, t.fileBrochure || "Brosura");
      } else if (mode === 'pdf' || mode === 'pdf-summary') {
        let slidesArray = Array.from(document.querySelectorAll('.pdf-presentation-slide'));
        if (slidesArray.length === 0) {
           setIsDownloading(null);
           return;
        }
        
        if (mode === 'pdf-summary') {
          slidesArray = slidesArray.slice(0, 4);
          const ctaSlide = document.querySelector('.pdf-cta-slide');
          if (ctaSlide) {
            slidesArray.push(ctaSlide as Element);
          }
        }

        const pdf = new jsPDF({
          orientation: "landscape",
          unit: "pt",
          format: [1280, 720]
        });

        // REGULA #5: Folosește domeniul oficial de producție ideeata.ai
        let pdfUrl = 'https://ideeata.ai/';
        const currentShareId = result?.id || generatedShareId;
        if (currentShareId) {
          pdfUrl = `https://ideeata.ai/shared/${currentShareId}`;
        }

        const pdfFooters: Record<string, string> = {
          ro: "Plan generat inteligent de IdeeaTa.ai",
          en: "Business plan smartly generated by IdeeaTa.ai",
          es: "Plan de negocios generado inteligentemente por IdeeaTa.ai"
        };

        for (let i = 0; i < slidesArray.length; i++) {
          const slideElement = slidesArray[i] as HTMLElement;
          const dataUrl = await toPng(slideElement, { quality: 1.0, pixelRatio: 2 });
          if (i > 0) pdf.addPage([1280, 720], "landscape");
          pdf.addImage(dataUrl, 'PNG', 0, 0, 1280, 720);
          
          // Dacă este ultimul slide (CTA), adăugăm un link invizibil peste toată pagina
          if (i === slidesArray.length - 1 && mode === 'pdf-summary') {
            pdf.link(1280/2 - 200, 720 - 180, 400, 100, { url: pdfUrl });
          }

          // Stamp footer on every page
          pdf.setTextColor(150, 150, 150); // Gray color
          pdf.setFontSize(14);
          pdf.text(pdfFooters[locale] || pdfFooters.ro, 640, 700, { align: 'center' });
          
          // Add invisible link covering the footer area on every page
          pdf.link(300, 680, 680, 40, { url: pdfUrl });
        }
        
        const suffix = mode === 'pdf-summary' ? `_${t.fileSummaryFree || "Sumar_Gratuit"}` : '';
        pdf.save(`IdeeaTa_${t.filePresentation || "Prezentare"}_${safeName}${suffix}.pdf`);
      } else if (mode === 'word') {
          const chartElement = document.getElementById("docx-export-chart-hidden");
          let chartDataUrl = null;
          if (chartElement) {
             try {
                chartDataUrl = await toPng(chartElement, { backgroundColor: '#ffffff' });
             } catch(e) { console.error(e); }
          }
          const planCurrency = result.selectedCurrency || currency || (locale === "es" || locale === "en" ? "EUR" : "LEI");
          const blob = await generateDocxBlob(result, chartDataUrl, locale, planCurrency);
          const link = document.createElement('a');
          link.href = URL.createObjectURL(blob);
          const safeName2 = result?.nume?.replace(/[^a-zA-Z0-9]/g, '_') || 'Business';
          link.download = `IdeeaTa_${t.fileDocument || "Document"}_${safeName2}.docx`;
          document.body.appendChild(link);
          link.click();
          document.body.removeChild(link);
      }

      await new Promise(resolve => setTimeout(resolve, 2000));
    } catch (e) {
      console.error("Eroare la generarea documentului", e);
      alert(t("errorSavingDocument", locale));
    } finally {
      setIsDownloading(null);
    }
  };

  return { downloadAction: handleDownloadAction };
}
